# Generated by Django 5.2.8 on 2025-12-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'managed': True, 'verbose_name': 'Vendor Profile', 'verbose_name_plural': 'Vendor Profile'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='vendorprofile',
            table='Vendor Profile',
        ),
    ]
