# Generated by Django 5.2.8 on 2025-12-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': True, 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
    ]
