# Generated by Django 5.2.8 on 2025-12-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True, 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
